name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
        
    - name: build_SenderSource
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o SenderSource test_GenerateBatteryParameters.cpp GenerateBatteryParameters.c
    
    - name: build_ReceiverSource
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o ReceiverSource test_ReceiveBatteryParameters.cpp ReceiveBatteryParameters.c
    
    - name: run_SenderSource
      run: ./SenderSource
      
    - name: run_ReceiverSource
      run: ./SenderSource | ./ReceiverSource
      
    - name: build_SenderExecutable
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o SenderExecutable SendBatteryParametersToConsole.c GenerateBatteryParameters.c
      
    - name: build_ReceiverExecutable
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o ReceiverExecutable ReceiveBatteryParametersFromConsole.c ReceiveBatteryParameters.c
    
    - name: run_SenderExecutable
      run: ./SenderExecutable > Sender.txt
      
    - name: run_ReceiverExecutable
      run: ./SenderExecutable | ./ReceiverExecutable

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: 'Upload Sender.txt'
      uses: actions/upload-artifact@v2
      with:
        name: Sender.txt
        path: ./*.txt
        retention-days: 10
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 10
