name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
        
    - name: build_SenderSource
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o SenderSource test_GenerateChargingParameters.cpp GenerateChargingParameters.c
       
    - name: run_SenderSource
      run: ./SenderSource
    
    - name: build_SenderExecutable
      run: g++ -Wall -Wextra -o SenderExecutable SendChargingParametersToConsole.c GenerateChargingParameters.c
     
    - name: run_SenderExecutable
      run: ./SenderExecutable # > Sender.txt
   
    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    # - name: 'Upload Sender.txt'
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Sender.txt
    #     path: ./*.txt
    #     retention-days: 10
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 10
